dist: focal
language: cpp
compiler:
- clang++
matrix:
  include:
    - os: osx
      osx_image: xcode10
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
            - ubuntu-toolchain-r-test
          packages:
            - clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
    - eval "${MATRIX_EVAL}"
script:
- ./build.sh
